name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: Moni0104/workflow/.github/workflows/helloworld@main
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.token }}
